spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # sentinel的控制面板路径
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#      filter:
#        enabled: false
  application:
    name: provider
server:
  port: 3333
# 配置限流路径
management:
  endpoints:
    web:
      exposure:
        include: '*'
rocketmq:
  name-server: 192.168.255.100:9876
  producer:
    group: myprovider


